spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#  这样可以看到sql语句
  jpa:
    show-sql: true    # 打印sql语句
    properties:
      hibernate:
      format_sql: true   # sql语句格式化
server:
  port: 8081   # 注意这里的端口号不要跟前端冲突